# https://hub.docker.com/r/gitlab/gitlab-ce
# command export APP_DISTRIBUTION=ee to cover the default gitlab-ce
# postgresql is in this container

version: '3.8'

services:

  gitlab:
    image: gitlab/gitlab-${APP_DISTRIBUTION}:${APP_VERSION}
    container_name: "${APP_CONTAINER_NAME}"
    hostname: "${DOMAIN}"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # external_url ${DOMAIN}
        # Add any other gitlab.rb configuration here, each on its own line
        # other
    stdin_open: true
    tty: true
    restart: always
    ports:
      - '9001:80'
      - '23:22'
    volumes:
      - ${VOLUMES_PATH_PREFIX}/gitlab/config:/etc/gitlab
      - ${VOLUMES_PATH_PREFIX}/gitlab/logs:/var/log/gitlab
      - ${VOLUMES_PATH_PREFIX}/gitlab/data:/var/opt/gitlab

networks:
  default:
      name: ${APP_NETWORK}